FROM alpine:3.7

MAINTAINER ivan@lagunovsky.com

RUN apk upgrade --update --no-cache && \
    apk add --update --no-cache \
    ca-certificates \
    rsync \
    curl \
    openssh \
    shadow \
    bash \
